Tablizo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

app/urls.py
from django.urls import path
from .views import (HomePageView, AboutPageView, OrderListView)
from .views import (OrdersDetailView, OrderCreateView, OrderUpdateView, OrderDeleteView)
from .views import (ReviewCreateView, ReviewDeleteView,ReviewDetailView, ReviewListView, ReviewUpdateView)
from django.urls import path
from . import views



urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('order/', OrderListView.as_view(), name='order'),
    path('order/<int:pk>', OrdersDetailView.as_view(), name='order_detail'),
    path('order/create', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/edit', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/delete', OrderDeleteView.as_view(), name='order_delete'),
    path('review/', ReviewListView.as_view(), name='review_list'),
    path('review/<int:pk>', ReviewDetailView.as_view(), name='review_detail'),
    path('review/create', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>/edit', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete', ReviewDeleteView.as_view(), name='review_delete'),
    path("cart", views.cart, name="cart"),
    path("checkout", views.checkout, name="checkout"),
    path("view-orders", views.view_orders, name="view_orders"),
    path("mark_order_as_delivered", views.mark_order_as_delivered, name="mark_order_as_delivered"),
    path("save_cart", views.save_cart, name="save_cart"),
    path("retrieve_saved_cart", views.retrieve_saved_cart, name="retrieve_saved_cart"),
]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import  reverse
from django.conf import settings


class UserProfile(models.Model):
    address = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField()
    your_order = models.TextField()
    status = models.CharField(max_length=20, default='pending')

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

    def get_absolute_url(self):
        return reverse("order_detail", kwargs={"pk": self.pk})


class Orderitem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    feedback = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.feedback

    def get_absolute_url(self):
        return reverse("review_detail", kwargs = {"pk": self.pk})


#Cart and UserOrder
class UserOrder(models.Model):
    username = models.CharField(max_length=200) #who placed the order
    order = models.TextField() #this will be a string representation of the cart from localStorage
    price = models.DecimalField(max_digits=6, decimal_places=2) #how much was the order
    time_of_order  = models.DateTimeField()
    delivered = models.BooleanField()

    class Meta:
        verbose_name = "User Order List"
        verbose_name_plural = "User Order List"

    def __str__(self):
        #overriding the string method to get a good representation of it in string format
        return f"Order placed by  : {self.username} on {self.time_of_order.date()} at {self.time_of_order.time().strftime('%H:%M:%S')}"

class SavedCarts(models.Model):
    username = models.CharField(max_length=200, primary_key=True)
    cart = models.TextField() #this will be a string representation of the cart from localStorage

    class Meta:
        verbose_name = "Saved Users Cart"
        verbose_name_plural = "Saved Users Cart"


    def __str__(self):
        #overriding the string method to get a good representation of it in string format
        return f"Saved cart for {self.username}"

app/templates/app/about.html
{% extends 'app/base.html' %}

{% block content %}
<div class="container">
    <div class="content my-3">
        <div class="card rounded-0 shadow">
            <div class="card-body">
                <div class="row justify-content-center" style="margin-top:20px;">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3864.2188716213036!2d120.97764377439555!3d14.41454268605005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397d383e4b73859%3A0x9cf21b9aff5fc996!2sTAGPUAN%20EXPRESS!5e0!3m2!1sen!2sph!4v1738314536646!5m2!1sen!2sph" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

                </div>
                <div class="row justify-content-center" style="margin-top:20px;">

                    <ul>
                        <p><h1>Located to Bacoor Cavite City</h1></p>
                        <li><h3> Reustaurant Address: Blk 33 Lot7 Phase 2 sampaguita st. Molino 6 Bacoor Cavite City, Philippines</h3></li>
                         <li><h3>  Contact no. 0916 768 5094</h3></li>
                         <li><h3>Email Address: marloubacudo97@gmail.com</h3></li>
                    </ul>

                </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tagpuan Express</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"
</head>
<body>
    {% include 'app/navbar.html' %}
    <main>
    {% if user.is_authenticated %}
        <a href="{% url 'profile' %}"><p>Hi {{ user.username }}</p></a>
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Log out</button>
        </form>
    {% else %}
        <p>You are not logged in</p>
    {% endif %}
{% block content %}
<!--pages-->
{% endblock content %}
</main>

        <script src="{% static 'js/base.js' %}" ></script>
</body>
</html>

app/templates/app/cart.html
{% extends 'app/base.html' %} {% block content %}

<div class="container-fluid">
    <div class="content my-3 px-2">
        <div class="card rounded-0 shadow">
            <div class="card-body">
                <div class="row justify-content-center">
                    <h2 id="cart_heading"></h2>
                    <fieldset class="pb-2 mb-3 border w-100">
                        <legend class="px-3 w-auto ml-3">Instructions:</legend>
                        <ul>
                            <li>Click the Item row to remove item from cart list. </li>
                            <li>Click checkout button to place order </li>
                        </ul>
                    </fieldset>
                    <table class="table table-bordered table-striped" id="card-tbl">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="text-center">#</th>
                                <th scope="col" class="text-center">Item Description</th>
                                <th scope="col" class="text-center">Price</th>
                            </tr>
                        </thead>
                        <tbody id="cart_body">
                        </tbody>
                    </table>


                    <h2>Total: <span class="badge badge-light border px-5 rounded-pill" id="total"></span></h2>
                </div>

                <div class="row justify-content-center">
                    <button id="checkout_button" type="button" class="btn btn-primary btn-block btn-lg rounded-pill" onclick="checkout()">Checkout</button>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/app/navbar.html
   <header>
        <a href="{% url 'home' %}">Home </a>
        <a href="{% url 'about' %}">About </a>
         <a href="{% url 'order' %}">Order </a>
         <a href="{% url 'login' %}">Login</a>
         <a href="{% url 'cart' %}">Cart</a>
          <a href="{% url 'review_list' %}" class="nav-link">Reviews</a>

   </header>

app/templates/app/order_create.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h1>New Order</h1>
    <form action="{% url 'order_create' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="id_user">User </label>
            <select id="id_user" name="user">
                {% for user in users %}
                <option value="{{user.pk}}" {% if user.pk == form.user.value %} selected {% endif %} >
                    {{user}}
                </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="id_name">Category</label>
            <select id="id_name" name="name">
                {% for category in categorys %}

                <option value="{{ category.pk }}"{% if category.pk == form.category.value %} selected {% endif %}>
                    {{ category }}
                </option>
                {% endfor %}
            </select>
        </div>

         <div>
            <label for="id_product">Product</label>
            <select id="id_product" name="product[]" multiple>

                {% for product in products %}
                <option value="{{ product.pk }}"{% if product.pk in form.product.value %} selected {% endif %}>
                    {{ product }}
                </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="id_created_at">Date</label>
            <input type="date" id="id_created_at" name="created_at"></input>
            {% for error in form.created_at.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>

        <div>
            <label for="id_created_at_time">Time</label>
            <input type="time" id="id_created_at_time" name="order_time" required />
            {% for error in form.created_at.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>

        <div>
            <label for="id_your_order">Notes </label>
            <input type="text" id="id_your_order" name="your_order"></input>
        </div>

        <div>
            <label for="id_status">Status </label>
            <input type="text" id="id_status" name="status"></input>
        </div>

        <div>
            <label for="id_price">Price</label>
            <input type="number" id="id_price" name="price" min="0" />
        </div>


       <div>
            <button type="submit" class="btn btn-primary">Finish Order</button>
        </div>


    </form>
{% endblock content %}

app/templates/app/order_delete.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h1>Edit Order</h1>
    <form action="{% url 'order_delete' object.pk %}" method="post" >
    {% csrf_token %}
        <p>Are you sure you want to delete your order{{post.title}}?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

app/templates/app/order_detail.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}

        <div class="order-entry">
            <h2><a href="">{{order.user}}</a></h2>
            <p>{{ order.status }}</p>
        </div>
        <a href="{% url 'order_update' order.pk %}"> + Edit Order</a>
        <a href="{% url 'order_delete' order.pk %}"> - Delete Order</a>

{% endblock content %}

app/templates/app/order_update.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h1>Edit Order</h1>
    <form action="{% url 'order_update' object.pk %}" method="post" >
    {% csrf_token %}
    {{form.as_p}}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load custom_tags %}
{% load humanize %} {% block content %}

<div class="container-fluid">
    <div class="content my-3 px-4">
        <div class="card shadow rounded-0">
            <div class="card-body">
                <div class="row justify-content-center">
                    {% if user.is_superuser %}
                    <fieldset class="pb-2 mb-3 border w-100">
                        <legend class="px-3 w-auto ml-3">Instructions:</legend>
                        <ul>
                            <li>Click the Order Row <small><i>(Red Filled Row)</i></small> to mark it as delivered</li>
                        </ul>
                    </fieldset>
                    {% else %}
                    <h2> List of Orders </h2>
                    {% endif %}

                    <table class="table" id="order-tbl">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Order ID</th>
                                <th scope="col">Ordered by</th>
                                <th scope="col">Date</th>
                                <th scope="col">Order</th>
                                <th scope="col">Amount Paid</th>
                            </tr>
                        </thead>
                        <tbody id="orders_table">
                            {% for row in rows %} {% if row.delivered %}
                            <tr class="table-success">
                                {% else %}
                                <tr class="table-danger mark-as-complete">
                                    {% endif %}
                                    <td>{{row.id}}</td>
                                    <td>{{row.username}}</td>
                                    <td>{{row.time_of_order}}</td>
                                    <td>
                                        <ul>
                                            {% for item in row.order|format_cart %}
                                            <li>{{item|format_cart_item}}</li>
                                            {% endfor %}
                                        </ul>
                                    </td>
                                    <td>Php {{row.price|floatformat:2|intcomma}}</td>
                                </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

app/templates/app/review_create.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="main-content">
    <form action="{% url 'review_create' %}" method="post" class="formm">
        <h1>New Review</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="input_button">
        <a href="{% url 'review_list' %}" class="input_button">Cancel</a>
    </form>
</div>
{% endblock content %}

app/templates/app/review_delete.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<div class="main-content">
    <form action="{% url 'review_create' %}" method="post" class="formm">
        <h1>New Review</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="input_button">
        <a href="{% url 'review_list' %}" class="input_button">Cancel</a>
    </form>
</div>
{% endblock content %}

app/templates/app/review_detail.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h2><a href="{% url 'review_list' %}" class="anchor">Back</a></h2>
    <fieldset>
        <legend><h2>{{ review.user }}</h2></legend>
        <p>{{ review.feedback }}</p>
        <a href="{% url 'review_update' review.pk %}" class="anchor">+ Edit Review</a>
        <a href="{% url 'review_delete' review.pk %}" class="anchor">- Delete Review</a>
    </fieldset>
{%  endblock content %}

app/templates/app/review_list.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <a href="{% url 'review_create' %}" class="add">+ Add Review</a>

    {% for review in reviews %}
        <a href="{% url 'review_detail' review.pk %}" class="review_link">
        <fieldset>
            <legend><h2>{{ review.user }}</h2></legend>
            <strong><p>{{ review }}</p></strong>
            <small style="color: black;">{{ review.created_date }}</small>
        </fieldset>
        </a>
    {% endfor %}
{%  endblock content %}

app/templates/app/review_update.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
    <h1>Edit Review</h1>
    <form action="{% url 'review_update' object.pk %}" method="post" class="formm">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="input_button">
        <a href="{% url 'review_detail' review.pk %}">Cancel</a>
    </form>
{%  endblock content %}